package net.starturtle27.netherexpansion;

import cpw.mods.fml.common.network.*;
import net.netherX.proxies.*;
import net.minecraft.util.*;
import net.minecraft.block.material.*;
import net.minecraft.creativetab.*;
import net.netherX.cursed.*;
import net.minecraft.potion.*;
import biomesoplenty.api.*;
import net.netherX.biomes.*;
import net.minecraft.world.biome.*;
import cpw.mods.fml.common.registry.*;
import cpw.mods.fml.common.*;
import net.minecraftforge.fluids.*;
import cpw.mods.fml.common.event.*;
import net.minecraft.block.*;
import net.minecraft.item.*;
import net.minecraft.entity.*;
import net.minecraftforge.common.*;

@Mod(modid = "NetherX", name = "NetherX", version = "1.2.2")
@NetworkMod(clientSideRequired = true, serverSideRequired = true)
public class NetherX
{
    @Mod.Instance("NetherX")
    public static NetherX instance;
    @SidedProxy(clientSide = "net.netherX.proxies.ClientProxyNX", serverSide = "net.netherX.proxies.CommonProxyNX")
    public static CommonProxyNX proxy;
    public static BiomeGenBaseNether BGBN;
    static int startEntityId;
    public static DamageSource bite;
    static boolean doGenerateTrees;
    static boolean doGenerateGiantMushrooms;
    static boolean doGenerateMagma;
    static boolean doGeneratePoisonLakes;
    static boolean doGenerateObsidianBeaches;
    static boolean doGenerateVenomiteOre;
    static boolean doGenerateNecromiteOre;
    static boolean doGenerateIchoriteOre;
    static boolean doGenerateNetherthorns;
    static boolean doGenerateCursedSoulSand;
    static boolean enableZPigMessage;
    static boolean enableZPigAngryness;
    static boolean enableNetherBiomes;
    static boolean netherFurnaceRequireNetherQuartz;
    public static boolean enableNetherRespawning;
    public static boolean laglessBrimspell;
    public static boolean enableObsidianPressurePlate;
    public static boolean enableIronCrafting;
    static int startIDBlock;
    static int startIDItem;
    public static Block netherShrineSummoning;
    public static Block soulglassPane;
    public static Block soulglassPaneTransparent;
    public static Block soulglassTransparent;
    public static Block oreIchorite;
    public static Block soulglass;
    public static Block oreMalite;
    public static Block oreNecromite;
    public static Block netherthorn;
    public static Block torchGlowstone;
    public static Block blockMalite;
    public static Block blockNecromite;
    public static Block netherShrine;
    public static Block vilewood;
    public static Block vileplanks;
    public static Block magma;
    public static Block netherbomb;
    public static Block enchantedSlowSand;
    public static Block poisonLiquid;
    public static Block crystalcauldron;
    public static Block poisoncrystalcauldron;
    public static Block netherfurnaceIdle;
    public static Block netherfurnaceBurning;
    public static Block stairsWoodVile;
    public static Block chiseledNetherrack;
    public static Block execrationTable;
    public static Block stairsNetherrack;
    public static Block glutrootBlock;
    public static Block chiseledNetherrackCharred;
    public static Block doorObsidian;
    public static Block plateObsidian;
    public static Block netherBrickSmoldering;
    public static BlockFire brimfire;
    public static Block netherrackPillar;
    public static Block mushroomVineBrown;
    public static Block vilewoodDoubleSlab;
    public static Block vilewoodSingleSlab;
    public static Block netherrackDoubleSlab;
    public static Block netherrackSingleSlab;
    public static Item malite;
    static EnumToolMaterial MALITE;
    static EnumToolMaterial NETHERRACK;
    static EnumToolMaterial NETHERRACKCURSED;
    static EnumToolMaterial NECROMITE;
    static EnumArmorMaterial MALITEARMOR;
    public static Item swordMalite;
    public static Item shovelMalite;
    public static Item pickaxeMalite;
    public static Item axeMalite;
    public static Item swordNetherrack;
    public static Item shovelNetherrack;
    public static Item pickaxeNetherrack;
    public static Item axeNetherrack;
    public static Item swordNecromite;
    public static Item shovelNecromite;
    public static Item pickaxeNecromite;
    public static Item axeNecromite;
    public static Item necromite;
    public static ItemNetherArmor helmetMalite;
    public static ItemNetherArmor plateMalite;
    public static ItemNetherArmor legsMalite;
    public static ItemNetherArmor bootsMalite;
    public static ItemNetherArmor helmetNecromite;
    public static ItemNetherArmor plateNecromite;
    public static ItemNetherArmor legsNecromite;
    public static ItemNetherArmor bootsNecromite;
    public static Item ichoriteShard;
    public static Item poisonbucketEmpty;
    public static Item poisonbucketPoison;
    public static Item poisonbucketLava;
    public static Item itemcrystalcauldron;
    public static Item ghastEgg;
    public static Item infernoStaff;
    public static Item magmaCrystal;
    public static ItemNetherArmor helmetMagma;
    public static ItemNetherArmor plateMagma;
    public static ItemNetherArmor legsMagma;
    public static ItemNetherArmor bootsMagma;
    public static Item bookCursed;
    public static Item blackpaper;
    public static Item swordNetherrackCursed;
    public static Item shovelNetherrackCursed;
    public static Item pickaxeNetherrackCursed;
    public static Item axeNetherrackCursed;
    public static Item swordVenomiteCursed;
    public static Item shovelVenomiteCursed;
    public static Item pickaxeVenomiteCursed;
    public static Item axeVenomiteCursed;
    public static Item swordNecromiteCursed;
    public static Item shovelNecromiteCursed;
    public static Item pickaxeNecromiteCursed;
    public static Item axeNecromiteCursed;
    public static Item infernoStaffCursed;
    public static Item glutroot;
    public static Item bowlGlutrootSoup;
    public static Item glutrootSeeds;
    public static Item doorObsidianPlacer;
    public static Item glutrootChocolateSeeds;
    public static Item obsidianBoat;
    public static Item bucketEmpty;
    public static Item glassBottle;
    public static Block oreNetherQuartz;
    EventManager eventmanager;
    OreManager oremanager;
    public static Fluid poison;

    public NetherX() {
        this.eventmanager = new EventManager();
        this.oremanager = new OreManager();
    }

    @Mod.EventHandler
    @Mod.Init
    public void preInit(final FMLPreInitializationEvent event) {
        final Configuration config = new Configuration(event.getSuggestedConfigurationFile());
        config.load();
        NetherX.doGenerateTrees = config.get("general", "Enable Vilewood Tree Generation", true).getBoolean(NetherX.doGenerateTrees);
        NetherX.doGenerateGiantMushrooms = config.get("general", "Enable Giant Mushrooms in the Mushroom Swamp", true).getBoolean(NetherX.doGenerateGiantMushrooms);
        NetherX.doGenerateMagma = config.get("general", "Enable Magma Generation", true).getBoolean(NetherX.doGenerateMagma);
        NetherX.doGeneratePoisonLakes = config.get("general", "Enable Poison Lake Generation", true).getBoolean(NetherX.doGeneratePoisonLakes);
        NetherX.doGenerateObsidianBeaches = config.get("general", "Enable Obsidian Beach Generation", true).getBoolean(NetherX.doGenerateObsidianBeaches);
        NetherX.doGenerateVenomiteOre = config.get("general", "Enable Venomite Ore Generation", true).getBoolean(NetherX.doGenerateVenomiteOre);
        NetherX.doGenerateNecromiteOre = config.get("general", "Enable Necromite Ore Generation", true).getBoolean(NetherX.doGenerateNecromiteOre);
        NetherX.doGenerateIchoriteOre = config.get("general", "Enable Ichorite Ore Generation", true).getBoolean(NetherX.doGenerateIchoriteOre);
        NetherX.doGenerateNetherthorns = config.get("general", "Enable Netherthorn Generation", true).getBoolean(NetherX.doGenerateNetherthorns);
        NetherX.doGenerateCursedSoulSand = config.get("general", "Enable Cursed Soulsand Generation", true).getBoolean(NetherX.doGenerateCursedSoulSand);
        NetherX.enableZPigAngryness = config.get("general", "Enable Zombie Pigmen Becoming Angry When Mining Nether Ores", true).getBoolean(NetherX.enableZPigAngryness);
        NetherX.enableZPigMessage = config.get("general", "Enable Angry Zombie Pigmen Chat Message when Mining Nether Ores", false).getBoolean(NetherX.enableZPigMessage);
        NetherX.enableNetherBiomes = config.get("general", "Enable Nether Biomes", true).getBoolean(NetherX.enableNetherBiomes);
        NetherX.enableNetherRespawning = config.get("general", "Enable Respawning in the Nether", false).getBoolean(NetherX.enableNetherRespawning);
        NetherX.netherFurnaceRequireNetherQuartz = config.get("general", "Makes the Nether Furnace require Nether Quartz to craft", false).getBoolean(NetherX.netherFurnaceRequireNetherQuartz);
        NetherX.laglessBrimspell = config.get("general", "Enable lagless brimspells (ie fire particles instead of a fire trail)", false).getBoolean(NetherX.laglessBrimspell);
        NetherX.enableObsidianPressurePlate = config.get("general", "Enable Obsidian Pressure Plates", true).getBoolean(NetherX.enableObsidianPressurePlate);
        NetherX.enableIronCrafting = config.get("general", "Enable Crafting Iron from Venomite and Ichorite", false).getBoolean(NetherX.enableIronCrafting);
        NetherX.startIDBlock = config.get("block", "Starting Block ID", 445).getInt();
        NetherX.startIDItem = config.get("block", "Starting Item ID", 10000).getInt();
        config.save();
    }

    @Mod.Init
    public void load(final FMLInitializationEvent event) {
        NetherX.soulglassPane = new BlockSoulPane(NetherX.startIDBlock, "glassSoul", "soulglass_pane_top", Material.glass, false, false).setHardness(0.3f).setStepSound(Block.soundGlassFootstep).setUnlocalizedName("soulglassPane");
        NetherX.soulglassPaneTransparent = new BlockSoulPane(NetherX.startIDBlock + 1, "glassSoul", "soulglass_pane_top", Material.glass, false, true).setHardness(0.3f).setStepSound(Block.soundGlassFootstep).setUnlocalizedName("soulglassPane").setCreativeTab((CreativeTabs)null);
        NetherX.soulglassTransparent = new BlockSoulGlass(NetherX.startIDBlock + 2, Material.glass, true).setHardness(0.5f).setStepSound(Block.soundGlassFootstep).setUnlocalizedName("soulglasstransparent").setTextureName("glassSoul_activated");
        NetherX.oreIchorite = new BlockIchorOre(NetherX.startIDBlock + 3).setHardness(2.5f).setResistance(4.0f).setStepSound(Block.soundStoneFootstep).setUnlocalizedName("oreIchorite").setTextureName("oreIchorite");
        NetherX.soulglass = new BlockSoulGlass(NetherX.startIDBlock + 4, Material.glass, false).setHardness(0.5f).setStepSound(Block.soundGlassFootstep).setUnlocalizedName("soulglass").setTextureName("glassSoul").setCreativeTab(CreativeTabs.tabBlock);
        NetherX.oreMalite = new BlockPoisonOre(NetherX.startIDBlock + 5).setHardness(2.0f).setResistance(3.0f).setStepSound(Block.soundStoneFootstep).setUnlocalizedName("oreMalite").setTextureName("oreMalite");
        NetherX.oreNecromite = new BlockNecroOre(NetherX.startIDBlock + 6).setHardness(2.5f).setResistance(4.0f).setStepSound(Block.soundStoneFootstep).setUnlocalizedName("oreNecromite").setTextureName("oreNecromite");
        NetherX.netherthorn = new BlockNetherThorn(NetherX.startIDBlock + 7).setHardness(0.0f).setStepSound(Block.soundGrassFootstep).setUnlocalizedName("netherthorn").setTextureName("netherthorn").setCreativeTab(CreativeTabs.tabDecorations);
        NetherX.torchGlowstone = new BlockNetherTorch(NetherX.startIDBlock + 8).setHardness(0.0f).setStepSound(Block.soundWoodFootstep).setUnlocalizedName("torchglowstone").setTextureName("torch_glowstone");
        NetherX.blockMalite = new BlockOreStorage(NetherX.startIDBlock + 9).setHardness(2.8f).setResistance(9.0f).setStepSound(Block.soundMetalFootstep).setUnlocalizedName("blockMalite").setTextureName("malite_block");
        NetherX.blockNecromite = new BlockOreStorage(NetherX.startIDBlock + 10).setHardness(3.8f).setResistance(10.0f).setStepSound(Block.soundMetalFootstep).setUnlocalizedName("blockNecromite").setTextureName("necromite_block");
        NetherX.netherShrine = new BlockShrine(NetherX.startIDBlock + 11).setHardness(4.0f).setLightValue(0.5f).setStepSound(Block.soundWoodFootstep).setUnlocalizedName("nethershrine").setTextureName("nether_shrine").setCreativeTab(CreativeTabs.tabRedstone);
        NetherX.vilewood = new BlockVileWood(NetherX.startIDBlock + 12).setHardness(1.8f).setStepSound(Block.soundWoodFootstep).setUnlocalizedName("log_vile").setTextureName("log_vile_top");
        NetherX.vileplanks = new Block(NetherX.startIDBlock + 13, Material.wood).setHardness(1.8f).setResistance(4.5f).setStepSound(Block.soundWoodFootstep).setUnlocalizedName("vilewood").setTextureName("planks_vile").setCreativeTab(CreativeTabs.tabBlock);
        NetherX.magma = new BlockMagma(NetherX.startIDBlock + 22).setHardness(0.4f).setLightValue(0.5f).setStepSound(Block.soundStoneFootstep).setUnlocalizedName("magma").setTextureName("magma");
        NetherX.netherbomb = new BlockNetherBomb(NetherX.startIDBlock + 15).setHardness(0.0f).setStepSound(Block.soundGrassFootstep).setUnlocalizedName("nbomb").setTextureName("nbomb");
        NetherX.enchantedSlowSand = new BlockEnchantedSoulSand(NetherX.startIDBlock - 1).setHardness(1.0f).setStepSound(Block.soundSandFootstep).setUnlocalizedName("magichellsand").setTextureName("soul_sand_enchanted");
        NetherX.poisonLiquid = new BlockPoison(NetherX.startIDBlock + 16, NetherX.poison, Material.water).setHardness(0.0f).setLightOpacity(3).setUnlocalizedName("poison").setTextureName("poison");
        NetherX.crystalcauldron = new BlockCrystalCauldron(NetherX.startIDBlock + 18).setHardness(2.0f).setUnlocalizedName("crystalcauldron").setTextureName("crystalcauldron");
        NetherX.poisoncrystalcauldron = new BlockPoisonCrystalCauldron(NetherX.startIDBlock + 19).setHardness(2.0f).setUnlocalizedName("poisoncrystalcauldron").setTextureName("crystalcauldron");
        NetherX.netherfurnaceIdle = new BlockNetherFurnace(NetherX.startIDBlock + 20, false).setHardness(2.3f).setStepSound(Block.soundStoneFootstep).setUnlocalizedName("netherfurnace").setCreativeTab(CreativeTabs.tabDecorations);
        NetherX.netherfurnaceBurning = new BlockNetherFurnace(NetherX.startIDBlock + 21, true).setHardness(2.3f).setStepSound(Block.soundStoneFootstep).setLightValue(0.875f).setUnlocalizedName("netherfurnace");
        NetherX.stairsWoodVile = new BlockVileStairs(NetherX.startIDBlock + 14, NetherX.vileplanks, 3).setUnlocalizedName("stairsWoodVile");
        NetherX.chiseledNetherrack = new Block(NetherX.startIDBlock + 23, Material.rock).setHardness(1.6f).setResistance(7.0f).setStepSound(Block.soundStoneFootstep).setUnlocalizedName("chiseledNetherrack").setCreativeTab(CreativeTabs.tabBlock).setTextureName("netherrack_chiseled");
        NetherX.execrationTable = new BlockExecrationTable(NetherX.startIDBlock + 24).setHardness(5.0f).setResistance(2000.0f).setUnlocalizedName("execrationTable").setTextureName("execration_table").setCreativeTab(CreativeTabs.tabDecorations);
        NetherX.stairsNetherrack = new BlockVileStairs(NetherX.startIDBlock + 25, NetherX.chiseledNetherrack, 0).setUnlocalizedName("stairsNetherBrick");
        NetherX.glutrootBlock = new BlockGlutroot(NetherX.startIDBlock + 26).setUnlocalizedName("glutroots").setTextureName("glutroot");
        NetherX.chiseledNetherrackCharred = new Block(NetherX.startIDBlock + 27, Material.rock).setHardness(1.6f).setResistance(7.0f).setStepSound(Block.soundStoneFootstep).setUnlocalizedName("chiseledNetherrackCharred").setCreativeTab(CreativeTabs.tabBlock).setTextureName("netherrack_chiseled_charred");
        NetherX.doorObsidian = new BlockObsidianDoor(NetherX.startIDBlock + 28, Material.rock).setHardness(50.0f).setResistance(2000.0f).setStepSound(Block.soundStoneFootstep).setUnlocalizedName("doorObsidian").setTextureName("door_obsidian");
        if (NetherX.enableObsidianPressurePlate) {
            NetherX.plateObsidian = new BlockObsidianPressurePlate(NetherX.startIDBlock + 29, "obsidian", Material.rock, EnumMobType.mobs).setHardness(25.0f).setStepSound(Block.soundStoneFootstep).setUnlocalizedName("pressurePlate");
        }
        NetherX.netherBrickSmoldering = new Block(NetherX.startIDBlock + 30, Material.rock).setHardness(2.0f).setResistance(10.0f).setStepSound(Block.soundStoneFootstep).setUnlocalizedName("netherBrickSmoldering").setCreativeTab(CreativeTabs.tabBlock).setTextureName("nether_brick_smoldering");
        NetherX.brimfire = (BlockFire)new BlockBrimFire(NetherX.startIDBlock + 31).setHardness(0.0f).setLightValue(1.0f).setStepSound(Block.soundWoodFootstep).setUnlocalizedName("brimfire").setTextureName("fire");
        NetherX.netherrackPillar = new BlockNetherrackPillar(NetherX.startIDBlock + 32).setHardness(1.8f).setStepSound(Block.soundStoneFootstep).setUnlocalizedName("pillarNetherrack").setTextureName("pillar_netherrack");
        NetherX.mushroomVineBrown = new BlockMushroomVine(NetherX.startIDBlock + 34).setHardness(0.2f).setStepSound(Block.soundClothFootstep).setUnlocalizedName("mushroomVineBrown").setTextureName("mushroom_vine_brown");
        NetherX.vilewoodDoubleSlab = new BlockVilewoodSlab(NetherX.startIDBlock + 35, true, Material.wood).setHardness(2.0f).setResistance(5.0f).setStepSound(Block.soundWoodFootstep).setUnlocalizedName("vilewoodSlabDouble").setTextureName("planks_vile");
        NetherX.vilewoodSingleSlab = new BlockVilewoodSlab(NetherX.startIDBlock + 36, false, Material.wood).setHardness(2.0f).setResistance(5.0f).setStepSound(Block.soundWoodFootstep).setUnlocalizedName("vilewoodSlabSingle").setTextureName("planks_vile").setCreativeTab(CreativeTabs.tabBlock);
        NetherX.netherrackDoubleSlab = new BlockNetherrackSlab(NetherX.startIDBlock + 37, true, Material.wood).setHardness(2.0f).setResistance(5.0f).setStepSound(Block.soundWoodFootstep).setUnlocalizedName("netherrackSlabDouble").setTextureName("netherrack_chiseled");
        NetherX.netherrackSingleSlab = new BlockNetherrackSlab(NetherX.startIDBlock + 38, false, Material.wood).setHardness(2.0f).setResistance(5.0f).setStepSound(Block.soundWoodFootstep).setUnlocalizedName("netherrackSlabSingle").setTextureName("netherrack_chiseled").setCreativeTab(CreativeTabs.tabBlock);
        NetherX.malite = new Item(NetherX.startIDItem + 1).setUnlocalizedName("malite").setCreativeTab(CreativeTabs.tabMaterials).setTextureName("malite");
        NetherX.swordMalite = new ItemMaliteSword(NetherX.startIDItem + 2, NetherX.MALITE).setUnlocalizedName("swordMalite").setTextureName("malite_sword");
        NetherX.shovelMalite = new ItemSpade(NetherX.startIDItem + 3, NetherX.MALITE).setUnlocalizedName("shovelMalite").setTextureName("malite_shovel");
        NetherX.pickaxeMalite = new ItemPickaxe(NetherX.startIDItem + 4, NetherX.MALITE).setUnlocalizedName("pickaxeMalite").setTextureName("malite_pickaxe");
        NetherX.axeMalite = new ItemAxe(NetherX.startIDItem + 5, NetherX.MALITE).setUnlocalizedName("hatchetMalite").setTextureName("malite_axe");
        NetherX.swordNetherrack = new ItemSword(NetherX.startIDItem + 6, NetherX.NETHERRACK).setUnlocalizedName("swordNetherrack").setTextureName("nether_sword");
        NetherX.shovelNetherrack = new ItemSpade(NetherX.startIDItem + 7, NetherX.NETHERRACK).setUnlocalizedName("shovelNetherrack").setTextureName("nether_shovel");
        NetherX.pickaxeNetherrack = new ItemPickaxe(NetherX.startIDItem + 8, NetherX.NETHERRACK).setUnlocalizedName("pickaxeNetherrack").setTextureName("nether_pickaxe");
        NetherX.axeNetherrack = new ItemAxe(NetherX.startIDItem + 9, NetherX.NETHERRACK).setUnlocalizedName("hatchetNetherrack").setTextureName("nether_axe");
        NetherX.swordNecromite = new ItemNecromiteSword(NetherX.startIDItem + 14, NetherX.NECROMITE).setUnlocalizedName("swordNecromite").setTextureName("necromite_sword");
        NetherX.shovelNecromite = new ItemSpade(NetherX.startIDItem + 15, NetherX.NECROMITE).setUnlocalizedName("shovelNecromite").setTextureName("necromite_shovel");
        NetherX.pickaxeNecromite = new ItemPickaxe(NetherX.startIDItem + 16, NetherX.NECROMITE).setUnlocalizedName("pickaxeNecromite").setTextureName("necromite_pickaxe");
        NetherX.axeNecromite = new ItemAxe(NetherX.startIDItem + 17, NetherX.NECROMITE).setUnlocalizedName("hatchetNecromite").setTextureName("necromite_axe");
        NetherX.necromite = new Item(NetherX.startIDItem + 18).setUnlocalizedName("necromite").setCreativeTab(CreativeTabs.tabMaterials).setTextureName("necromite");
        NetherX.helmetMalite = (ItemNetherArmor)new ItemNetherArmor(NetherX.startIDItem + 19, NetherX.MALITEARMOR, 2, 0).setUnlocalizedName("helmetMalite").setTextureName("poison_helmet");
        NetherX.plateMalite = (ItemNetherArmor)new ItemNetherArmor(NetherX.startIDItem + 20, NetherX.MALITEARMOR, 2, 1).setUnlocalizedName("chestplateMalite").setTextureName("poison_chestplate");
        NetherX.legsMalite = (ItemNetherArmor)new ItemNetherArmor(NetherX.startIDItem + 21, NetherX.MALITEARMOR, 2, 2).setUnlocalizedName("leggingsMalite").setTextureName("poison_leggings");
        NetherX.bootsMalite = (ItemNetherArmor)new ItemNetherArmor(NetherX.startIDItem + 22, NetherX.MALITEARMOR, 2, 3).setUnlocalizedName("bootsMalite").setTextureName("poison_boots");
        NetherX.helmetNecromite = (ItemNetherArmor)new ItemNetherArmor(NetherX.startIDItem + 23, EnumArmorMaterial.DIAMOND, 3, 0).setUnlocalizedName("helmetNecromite").setTextureName("necro_helmet");
        NetherX.plateNecromite = (ItemNetherArmor)new ItemNetherArmor(NetherX.startIDItem + 24, EnumArmorMaterial.DIAMOND, 3, 1).setUnlocalizedName("chestplateNecromite").setTextureName("necro_chestplate");
        NetherX.legsNecromite = (ItemNetherArmor)new ItemNetherArmor(NetherX.startIDItem + 25, EnumArmorMaterial.DIAMOND, 3, 2).setUnlocalizedName("leggingsNecromite").setTextureName("necro_leggings");
        NetherX.bootsNecromite = (ItemNetherArmor)new ItemNetherArmor(NetherX.startIDItem + 26, EnumArmorMaterial.DIAMOND, 3, 3).setUnlocalizedName("bootsNecromite").setTextureName("necro_boots");
        NetherX.ichoriteShard = new ItemIchoriteShard(NetherX.startIDItem + 27).setUnlocalizedName("ichoriteShard").setPotionEffect(PotionHelper.redstoneEffect).setTextureName("ichorite_shard").setCreativeTab(CreativeTabs.tabMaterials);
        NetherX.poisonbucketEmpty = new ItemPoisonBucket(NetherX.startIDItem + 28, 0).setUnlocalizedName("poisonbucket").setMaxStackSize(16).setTextureName("poisonbucket_empty");
        NetherX.poisonbucketPoison = new ItemPoisonBucket(NetherX.startIDItem + 29, NetherX.poisonLiquid.blockID).setUnlocalizedName("bucketPoison").setContainerItem(NetherX.poisonbucketEmpty).setTextureName("poisonbucket_poison");
        NetherX.poisonbucketLava = new ItemPoisonBucket(NetherX.startIDItem + 30, Block.lavaMoving.blockID).setUnlocalizedName("bucketLava").setContainerItem(NetherX.poisonbucketEmpty).setTextureName("poisonbucket_lava");
        NetherX.itemcrystalcauldron = new ItemReed(NetherX.startIDItem + 31, NetherX.crystalcauldron).setUnlocalizedName("itemcrystalcauldron").setCreativeTab(CreativeTabs.tabBrewing).setTextureName("crystalcauldron");
        NetherX.ghastEgg = new Item(NetherX.startIDItem + 32).setUnlocalizedName("ghastEgg").setCreativeTab(CreativeTabs.tabMisc).setTextureName("spawn_egg");
        NetherX.infernoStaff = new ItemInfernoStaff(NetherX.startIDItem + 33).setUnlocalizedName("infernoStaff").setCreativeTab(CreativeTabs.tabCombat).setTextureName("inferno_staff").setMaxDamage(250);
        NetherX.magmaCrystal = new Item(NetherX.startIDItem + 34).setUnlocalizedName("magmaCrystal").setCreativeTab(CreativeTabs.tabMaterials).setTextureName("magma_crystal");
        NetherX.helmetMagma = (ItemNetherArmor)new ItemNetherArmor(NetherX.startIDItem + 36, EnumArmorMaterial.CHAIN, 3, 0).setUnlocalizedName("helmetMagma").setTextureName("magma_helmet");
        NetherX.plateMagma = (ItemNetherArmor)new ItemNetherArmor(NetherX.startIDItem + 37, EnumArmorMaterial.CHAIN, 3, 1).setUnlocalizedName("chestplateMagma").setTextureName("magma_chestplate");
        NetherX.legsMagma = (ItemNetherArmor)new ItemNetherArmor(NetherX.startIDItem + 38, EnumArmorMaterial.CHAIN, 3, 2).setUnlocalizedName("leggingsMagma").setTextureName("magma_leggings");
        NetherX.bootsMagma = (ItemNetherArmor)new ItemNetherArmor(NetherX.startIDItem + 39, EnumArmorMaterial.CHAIN, 3, 3).setUnlocalizedName("bootsMagma").setTextureName("magma_boots");
        NetherX.bookCursed = new ItemBook(NetherX.startIDItem + 40).setUnlocalizedName("bookCursed").setCreativeTab(CreativeTabs.tabMisc).setTextureName("book_cursed");
        NetherX.blackpaper = new Item(NetherX.startIDItem + 42).setUnlocalizedName("blackpaper").setCreativeTab(CreativeTabs.tabMisc).setTextureName("black_paper");
        NetherX.swordNetherrackCursed = new ItemCursedSword(NetherX.startIDItem + 43, NetherX.NETHERRACKCURSED).setUnlocalizedName("swordNetherrackCursed").setTextureName("nether_sword");
        NetherX.shovelNetherrackCursed = new ItemCursedSpade(NetherX.startIDItem + 44, NetherX.NETHERRACKCURSED).setUnlocalizedName("shovelNetherrack").setTextureName("nether_shovel");
        NetherX.pickaxeNetherrackCursed = new ItemCursedPickaxe(NetherX.startIDItem + 45, NetherX.NETHERRACKCURSED).setUnlocalizedName("pickaxeNetherrack").setTextureName("nether_pickaxe");
        NetherX.axeNetherrackCursed = new ItemCursedAxe(NetherX.startIDItem + 46, NetherX.NETHERRACKCURSED).setUnlocalizedName("hatchetNetherrack").setTextureName("nether_axe");
        NetherX.swordVenomiteCursed = new ItemMaliteSword(NetherX.startIDItem + 47, NetherX.MALITE).setUnlocalizedName("swordMalite").setTextureName("malite_sword").setCreativeTab((CreativeTabs)null);
        NetherX.shovelVenomiteCursed = new ItemCursedSpade(NetherX.startIDItem + 48, NetherX.MALITE).setUnlocalizedName("shovelMalite").setTextureName("malite_shovel");
        NetherX.pickaxeVenomiteCursed = new ItemCursedPickaxe(NetherX.startIDItem + 49, NetherX.MALITE).setUnlocalizedName("pickaxeMalite").setTextureName("malite_pickaxe");
        NetherX.axeVenomiteCursed = new ItemCursedAxe(NetherX.startIDItem + 50, NetherX.MALITE).setUnlocalizedName("hatchetMalite").setTextureName("malite_axe");
        NetherX.swordNecromiteCursed = new ItemNecromiteSword(NetherX.startIDItem + 51, NetherX.NECROMITE).setUnlocalizedName("swordNecromite").setTextureName("necromite_sword").setCreativeTab((CreativeTabs)null);
        NetherX.shovelNecromiteCursed = new ItemCursedSpade(NetherX.startIDItem + 52, NetherX.NECROMITE).setUnlocalizedName("shovelNecromite").setTextureName("necromite_shovel");
        NetherX.pickaxeNecromiteCursed = new ItemCursedPickaxe(NetherX.startIDItem + 53, NetherX.NECROMITE).setUnlocalizedName("pickaxeNecromite").setTextureName("necromite_pickaxe");
        NetherX.axeNecromiteCursed = new ItemCursedAxe(NetherX.startIDItem + 54, NetherX.NECROMITE).setUnlocalizedName("hatchetNecromite").setTextureName("necromite_axe");
        NetherX.infernoStaffCursed = new ItemInfernoStaff(NetherX.startIDItem + 55).setUnlocalizedName("infernoStaff").setCreativeTab(CreativeTabs.tabCombat).setTextureName("inferno_staff").setMaxDamage(250).setCreativeTab((CreativeTabs)null);
        NetherX.glutroot = new ItemFood(NetherX.startIDItem + 56, 5, 0.6f, false).setPotionEffect(Potion.digSlowdown.id, 30, 0, 0.4f).setUnlocalizedName("glutroots").setTextureName("glutroot");
        NetherX.bowlGlutrootSoup = new ItemSoup(NetherX.startIDItem + 57, 7).setPotionEffect(Potion.digSlowdown.id, 30, 0, 0.3f).setUnlocalizedName("glutrootSoup").setTextureName("glutroot_soup");
        NetherX.glutrootSeeds = new ItemGlutrootSeeds(NetherX.startIDItem + 58, NetherX.glutrootBlock.blockID, Block.slowSand.blockID).setUnlocalizedName("glutrootSeeds").setTextureName("glutroot_seeds");
        NetherX.doorObsidianPlacer = new ItemObsidianDoor(NetherX.startIDItem + 59, Material.rock).setUnlocalizedName("doorObsidian").setTextureName("door_obsidian");
        NetherX.glutrootChocolateSeeds = new ItemFood(NetherX.startIDItem + 60, 3, 0.3f, true).setPotionEffect(Potion.digSpeed.id, 30, 0, 0.4f).setUnlocalizedName("glutrootsChocolate").setTextureName("glutroot_seeds_chocolate").setCreativeTab((CreativeTabs)null);
        NetherX.obsidianBoat = new ItemObsidianBoat(NetherX.startIDItem + 61).setUnlocalizedName("obsidianboat").setTextureName("lavaboat");
        Biomes.netherBiomes.add(BiomeGenBaseNether.souldesert);
        Biomes.netherBiomes.add(BiomeGenBaseNether.vileswamp);
        Biomes.netherBiomes.add(BiomeGenBaseNether.stalactite);
        MinecraftForge.EVENT_BUS.register((Object)new NXLavaResistant());
        MinecraftForge.EVENT_BUS.register((Object)new LiquidHandler());
        if (NetherX.enableNetherBiomes && !Loader.isModLoaded("BiomesOPlenty")) {
            DimensionManager.unregisterProviderType(-1);
            DimensionManager.registerProviderType(-1, (Class)WorldProviderNXHell.class, true);
            BiomeGenBase.biomeList[BiomeGenBase.hell.biomeID].topBlock = (byte)Block.netherrack.blockID;
            BiomeGenBase.biomeList[BiomeGenBase.hell.biomeID].fillerBlock = (byte)Block.netherrack.blockID;
        }
        MinecraftForge.setToolClass(NetherX.pickaxeNetherrack, "pickaxe", 1);
        MinecraftForge.setToolClass(NetherX.pickaxeMalite, "pickaxe", 2);
        MinecraftForge.setToolClass(NetherX.pickaxeNecromite, "pickaxe", 3);
        MinecraftForge.setToolClass(NetherX.pickaxeNetherrackCursed, "pickaxe", 2);
        MinecraftForge.setToolClass(NetherX.pickaxeVenomiteCursed, "pickaxe", 2);
        MinecraftForge.setToolClass(NetherX.pickaxeNecromiteCursed, "pickaxe", 3);
        NetherX.proxy.registerRenderThings();
        NetherX.netherShrineSummoning = new BlockSummoningShrine(443).setBlockUnbreakable().setResistance(6000000.0f).setLightValue(0.5f).setStepSound(Block.soundWoodFootstep).setUnlocalizedName("nethershrine").setTextureName("nether_shrine");
        GameRegistry.registerTileEntity((Class)TileEntityNetherFurnace.class, "tileentityNFurnace");
        GameRegistry.registerTileEntity((Class)TileEntityCurse.class, "tileentityCurse");
        Item.itemsList[Item.bucketEmpty.itemID] = null;
        Item.itemsList[Item.bucketEmpty.itemID] = NetherX.bucketEmpty;
        Item.itemsList[Item.glassBottle.itemID] = null;
        Item.itemsList[Item.glassBottle.itemID] = NetherX.glassBottle;
        Block.blocksList[Block.oreNetherQuartz.blockID] = null;
        NetherX.oreNetherQuartz = new BlockNXQuartzOre(153).setHardness(3.0f).setResistance(5.0f).setStepSound(Block.soundStoneFootstep).setUnlocalizedName("netherquartz").setTextureName("quartz_ore");
        Block.blocksList[Block.oreNetherQuartz.blockID] = NetherX.oreNetherQuartz;
        GameRegistry.registerBlock(NetherX.oreNetherQuartz);
        GameRegistry.registerBlock(NetherX.oreIchorite);
        LanguageRegistry.addName((Object)NetherX.oreIchorite, "Ichorite Ore");
        GameRegistry.registerBlock(NetherX.soulglassTransparent);
        GameRegistry.registerBlock(NetherX.soulglass);
        LanguageRegistry.addName((Object)NetherX.soulglass, "Soul Glass");
        GameRegistry.registerBlock(NetherX.soulglassPaneTransparent);
        GameRegistry.registerBlock(NetherX.soulglassPane);
        LanguageRegistry.addName((Object)NetherX.soulglassPane, "Soul Glass Pane");
        GameRegistry.registerBlock(NetherX.oreMalite);
        MinecraftForge.setBlockHarvestLevel(NetherX.oreMalite, "pickaxe", 1);
        LanguageRegistry.addName((Object)NetherX.oreMalite, "Venomite Ore");
        GameRegistry.registerBlock(NetherX.oreNecromite);
        MinecraftForge.setBlockHarvestLevel(NetherX.oreNecromite, "pickaxe", 2);
        LanguageRegistry.addName((Object)NetherX.oreNecromite, "Necromite Ore");
        GameRegistry.registerBlock(NetherX.netherthorn);
        LanguageRegistry.addName((Object)NetherX.netherthorn, "Netherthorn");
        GameRegistry.registerBlock(NetherX.torchGlowstone);
        LanguageRegistry.addName((Object)NetherX.torchGlowstone, "Glowstone Torch");
        GameRegistry.registerBlock(NetherX.blockMalite);
        LanguageRegistry.addName((Object)NetherX.blockMalite, "Venomite Block");
        GameRegistry.registerBlock(NetherX.blockNecromite);
        LanguageRegistry.addName((Object)NetherX.blockNecromite, "Necromite Block");
        GameRegistry.registerBlock(NetherX.vilewood);
        LanguageRegistry.addName((Object)NetherX.vilewood, "Vilewood");
        GameRegistry.registerBlock(NetherX.vileplanks);
        LanguageRegistry.addName((Object)NetherX.vileplanks, "Vilewood Planks");
        GameRegistry.registerBlock(NetherX.netherShrine);
        LanguageRegistry.addName((Object)NetherX.netherShrine, "Ghast Shrine");
        GameRegistry.registerBlock(NetherX.netherShrineSummoning);
        LanguageRegistry.addName((Object)NetherX.netherShrineSummoning, "Ghast Shrine");
        GameRegistry.registerBlock(NetherX.magma);
        LanguageRegistry.addName((Object)NetherX.magma, "Magma");
        GameRegistry.registerBlock(NetherX.netherbomb);
        LanguageRegistry.addName((Object)NetherX.netherbomb, "Nether Bomb");
        GameRegistry.registerBlock(NetherX.enchantedSlowSand);
        LanguageRegistry.addName((Object)NetherX.enchantedSlowSand, "Cursed Soul Sand");
        GameRegistry.registerBlock(NetherX.poisonLiquid);
        LanguageRegistry.addName((Object)NetherX.poisonLiquid, "Poison");
        GameRegistry.registerBlock(NetherX.crystalcauldron);
        LanguageRegistry.addName((Object)NetherX.crystalcauldron, "Crystal Cauldron");
        GameRegistry.registerBlock(NetherX.poisoncrystalcauldron);
        LanguageRegistry.addName((Object)NetherX.poisoncrystalcauldron, "Crystal Cauldron");
        GameRegistry.registerBlock(NetherX.netherfurnaceIdle);
        LanguageRegistry.addName((Object)NetherX.netherfurnaceIdle, "Nether Furnace");
        GameRegistry.registerBlock(NetherX.netherfurnaceBurning);
        LanguageRegistry.addName((Object)NetherX.netherfurnaceBurning, "Nether Furnace");
        GameRegistry.registerBlock(NetherX.stairsWoodVile);
        LanguageRegistry.addName((Object)NetherX.stairsWoodVile, "Vilewood Stairs");
        GameRegistry.registerBlock(NetherX.chiseledNetherrack);
        LanguageRegistry.addName((Object)NetherX.chiseledNetherrack, "Chiseled Netherrack");
        GameRegistry.registerBlock(NetherX.chiseledNetherrackCharred);
        LanguageRegistry.addName((Object)NetherX.chiseledNetherrackCharred, "Charred Chiseled Netherrack");
        GameRegistry.registerBlock(NetherX.netherrackPillar);
        LanguageRegistry.addName((Object)NetherX.netherrackPillar, "Nether Column");
        GameRegistry.registerBlock(NetherX.execrationTable);
        LanguageRegistry.addName((Object)NetherX.execrationTable, "Execration Table");
        LanguageRegistry.addName((Object)NetherX.malite, "Venomite Ingot");
        LanguageRegistry.addName((Object)NetherX.swordMalite, "Venomite Sword");
        LanguageRegistry.addName((Object)NetherX.shovelMalite, "Venomite Shovel");
        LanguageRegistry.addName((Object)NetherX.pickaxeMalite, "Venomite Pickaxe");
        LanguageRegistry.addName((Object)NetherX.axeMalite, "Venomite Axe");
        LanguageRegistry.addName((Object)NetherX.swordNetherrack, "Netherrack Sword");
        LanguageRegistry.addName((Object)NetherX.shovelNetherrack, "Netherrack Shovel");
        LanguageRegistry.addName((Object)NetherX.pickaxeNetherrack, "Netherrack Pickaxe");
        LanguageRegistry.addName((Object)NetherX.axeNetherrack, "Netherrack Axe");
        LanguageRegistry.addName((Object)NetherX.swordNecromite, "Necromite Sword");
        LanguageRegistry.addName((Object)NetherX.shovelNecromite, "Necromite Shovel");
        LanguageRegistry.addName((Object)NetherX.pickaxeNecromite, "Necromite Pickaxe");
        LanguageRegistry.addName((Object)NetherX.axeNecromite, "Necromite Axe");
        LanguageRegistry.addName((Object)NetherX.necromite, "Necromite Gemstone");
        LanguageRegistry.addName((Object)NetherX.helmetMalite, "Venomite Helmet");
        LanguageRegistry.addName((Object)NetherX.plateMalite, "Venomite Chestplate");
        LanguageRegistry.addName((Object)NetherX.legsMalite, "Venomite Leggings");
        LanguageRegistry.addName((Object)NetherX.bootsMalite, "Venomite Boots");
        LanguageRegistry.addName((Object)NetherX.helmetNecromite, "Necromite Helmet");
        LanguageRegistry.addName((Object)NetherX.plateNecromite, "Necromite Chestplate");
        LanguageRegistry.addName((Object)NetherX.legsNecromite, "Necromite Leggings");
        LanguageRegistry.addName((Object)NetherX.bootsNecromite, "Necromite Boots");
        LanguageRegistry.addName((Object)NetherX.helmetMagma, "Magma Helmet");
        LanguageRegistry.addName((Object)NetherX.plateMagma, "Magma Chestplate");
        LanguageRegistry.addName((Object)NetherX.legsMagma, "Magma Leggings");
        LanguageRegistry.addName((Object)NetherX.bootsMagma, "Magma Boots");
        LanguageRegistry.addName((Object)NetherX.ichoriteShard, "Ichorite Shard");
        LanguageRegistry.addName((Object)NetherX.poisonbucketEmpty, "Venomite Bucket");
        LanguageRegistry.addName((Object)NetherX.poisonbucketLava, "Lava Bucket");
        LanguageRegistry.addName((Object)NetherX.poisonbucketPoison, "Poison Bucket");
        LanguageRegistry.addName((Object)NetherX.itemcrystalcauldron, "Crystal Cauldron");
        LanguageRegistry.addName((Object)NetherX.ghastEgg, "Ghast Egg");
        LanguageRegistry.addName((Object)NetherX.infernoStaff, "Inferno Staff");
        LanguageRegistry.addName((Object)NetherX.magmaCrystal, "Magma Crystal");
        LanguageRegistry.addName((Object)NetherX.bookCursed, "Cursed Book");
        LanguageRegistry.addName((Object)NetherX.blackpaper, "Cursed Paper");
        GameRegistry.registerBlock(NetherX.stairsNetherrack);
        LanguageRegistry.addName((Object)NetherX.stairsNetherrack, "Chiseled Netherrack Stairs");
        GameRegistry.registerBlock(NetherX.glutrootBlock);
        LanguageRegistry.addName((Object)NetherX.glutrootBlock, "Glutroot");
        GameRegistry.registerBlock(NetherX.doorObsidian);
        LanguageRegistry.addName((Object)NetherX.doorObsidian, "Obsidian Door");
        LanguageRegistry.addName((Object)NetherX.doorObsidianPlacer, "Obsidian Door");
        LanguageRegistry.addName((Object)NetherX.obsidianBoat, "Obsidian Boat");
        if (NetherX.enableObsidianPressurePlate) {
            GameRegistry.registerBlock(NetherX.plateObsidian);
        }
        LanguageRegistry.addName((Object)NetherX.glutroot, "Glutroot");
        LanguageRegistry.addName((Object)NetherX.bowlGlutrootSoup, "Glutroot Soup");
        LanguageRegistry.addName((Object)NetherX.glutrootSeeds, "Glutroot Seeds");
        LanguageRegistry.addName((Object)NetherX.glutrootChocolateSeeds, "Super-Sweetened Chocolate Covered Glutroot Seeds");
        GameRegistry.registerBlock((Block)NetherX.brimfire);
        LanguageRegistry.addName((Object)NetherX.brimfire, "Brimfire");
        GameRegistry.registerBlock(NetherX.mushroomVineBrown);
        LanguageRegistry.addName((Object)NetherX.mushroomVineBrown, "Fungal Strands");
        GameRegistry.registerBlock(NetherX.vilewoodSingleSlab);
        GameRegistry.registerBlock(NetherX.vilewoodDoubleSlab);
        LanguageRegistry.addName((Object)NetherX.vilewoodSingleSlab, "Vilewood Slab");
        LanguageRegistry.addName((Object)NetherX.vilewoodDoubleSlab, "Vilewood Slab");
        GameRegistry.registerBlock(NetherX.netherrackSingleSlab);
        GameRegistry.registerBlock(NetherX.netherrackDoubleSlab);
        LanguageRegistry.addName((Object)NetherX.netherrackSingleSlab, "Chiseled Netherrack Slab");
        LanguageRegistry.addName((Object)NetherX.netherrackDoubleSlab, "Chiseled Netherrack Slab");
        LanguageRegistry.addName((Object)NetherX.swordNetherrackCursed, "Netherrack Sword");
        EntityRegistry.registerModEntity((Class)EntityGlutton.class, "Glutton", NetherX.startEntityId + 1, (Object)this, 80, 4, true);
        EntityRegistry.registerGlobalEntityID((Class)EntityGlutton.class, "Glutton", EntityRegistry.findGlobalUniqueEntityId());
        LanguageRegistry.instance().addStringLocalization("entity.NetherX.Glutton.name", "Glutton");
        EntityRegistry.addSpawn((Class)EntityGlutton.class, 15, 4, 4, EnumCreatureType.creature, new BiomeGenBase[] { BiomeGenBase.hell, BiomeGenBaseNether.vileswamp, BiomeGenBaseNether.stalactite });
        registerEntityEgg((Class<? extends Entity>)EntityGlutton.class, 14702107, 8538673);
        EntityRegistry.addSpawn((Class)EntityFireCow.class, 10, 1, 2, EnumCreatureType.monster, new BiomeGenBase[] { BiomeGenBase.hell });
        EntityRegistry.registerModEntity((Class)EntityFireCow.class, "FireCow", NetherX.startEntityId + 2, (Object)this, 80, 4, true);
        EntityRegistry.registerGlobalEntityID((Class)EntityFireCow.class, "FireCow", EntityRegistry.findGlobalUniqueEntityId());
        LanguageRegistry.instance().addStringLocalization("entity.NetherX.FireCow.name", "Blazing Charger");
        registerEntityEgg((Class<? extends Entity>)EntityFireCow.class, 12394528, 14701339);
        EntityRegistry.addSpawn((Class)EntityNetherSpider.class, 11, 4, 4, EnumCreatureType.monster, new BiomeGenBase[] { BiomeGenBase.hell });
        EntityRegistry.addSpawn((Class)EntityNetherSpider.class, 6, 1, 1, EnumCreatureType.monster, new BiomeGenBase[] { BiomeGenBaseNether.souldesert, BiomeGenBaseNether.stalactite, BiomeGenBaseNether.vileswamp });
        EntityRegistry.registerModEntity((Class)EntityNetherSpider.class, "NetherSpider", NetherX.startEntityId + 3, (Object)this, 80, 4, true);
        EntityRegistry.registerGlobalEntityID((Class)EntityNetherSpider.class, "NetherSpider", EntityRegistry.findGlobalUniqueEntityId());
        LanguageRegistry.instance().addStringLocalization("entity.NetherX.NetherSpider.name", "Nether Spider");
        registerEntityEgg((Class<? extends Entity>)EntityNetherSpider.class, 7678216, 11013646);
        EntityRegistry.registerModEntity((Class)EntityPigman.class, "Pigman", NetherX.startEntityId + 4, (Object)this, 80, 4, true);
        LanguageRegistry.instance().addStringLocalization("entity.NetherX.Pigman.name", "Pigman");
        EntityRegistry.registerGlobalEntityID((Class)EntityPigman.class, "Pigman", EntityRegistry.findGlobalUniqueEntityId());
        registerEntityEgg((Class<? extends Entity>)EntityPigman.class, 15373203, 4862506);
        EntityRegistry.registerModEntity((Class)EntityGhastQueen.class, "GhastQueen", NetherX.startEntityId + 6, (Object)this, 80, 4, true);
        EntityRegistry.registerGlobalEntityID((Class)EntityGhastQueen.class, "GhastQueen", EntityRegistry.findGlobalUniqueEntityId());
        LanguageRegistry.instance().addStringLocalization("entity.NetherX.GhastQueen.name", "Ghast Queen");
        registerEntityEgg((Class<? extends Entity>)EntityGhastQueen.class, 16382457, 14925598);
        EntityRegistry.addSpawn((Class)EntityBrimspell.class, 9, 4, 4, EnumCreatureType.monster, new BiomeGenBase[] { BiomeGenBase.hell, BiomeGenBaseNether.stalactite });
        EntityRegistry.registerModEntity((Class)EntityBrimspell.class, "Brimspell", NetherX.startEntityId + 7, (Object)this, 80, 4, true);
        EntityRegistry.registerGlobalEntityID((Class)EntityBrimspell.class, "Brimspell", EntityRegistry.findGlobalUniqueEntityId());
        LanguageRegistry.instance().addStringLocalization("entity.NetherX.Brimspell.name", "Brimspell");
        registerEntityEgg((Class<? extends Entity>)EntityBrimspell.class, 16756224, 5064766);
        EntityRegistry.registerModEntity((Class)EntityPigZombieConvertable.class, "PigZombie", NetherX.startEntityId + 8, (Object)this, 80, 4, true);
        EntityRegistry.registerGlobalEntityID((Class)EntityPigZombieConvertable.class, "PigZombie", EntityRegistry.findGlobalUniqueEntityId());
        LanguageRegistry.instance().addStringLocalization("entity.NetherX.PigZombie.name", "Zombie Pigmen");
        EntityRegistry.addSpawn((Class)EntityInfernoSpider.class, 12, 5, 5, EnumCreatureType.monster, new BiomeGenBase[] { BiomeGenBaseNether.souldesert });
        EntityRegistry.registerModEntity((Class)EntityInfernoSpider.class, "InfernoSpider", NetherX.startEntityId + 9, (Object)this, 80, 4, true);
        EntityRegistry.registerGlobalEntityID((Class)EntityInfernoSpider.class, "InfernoSpider", EntityRegistry.findGlobalUniqueEntityId());
        LanguageRegistry.instance().addStringLocalization("entity.NetherX.InfernoSpider.name", "Inferno Spider");
        registerEntityEgg((Class<? extends Entity>)EntityInfernoSpider.class, 13189130, 11013646);
        EntityRegistry.registerModEntity((Class)EntityObsidianBoat.class, "ObsidianBoat", NetherX.startEntityId + 10, (Object)this, 80, 4, true);
        EntityRegistry.registerGlobalEntityID((Class)EntityObsidianBoat.class, "ObsidianBoat", EntityRegistry.findGlobalUniqueEntityId());
        LanguageRegistry.instance().addStringLocalization("entity.NetherX.ObsidianBoat.name", "Obsidian Boat");
        LanguageRegistry.instance().addStringLocalization("death.attack.bite", "%1$s became food for Gluttons");
        GameRegistry.addSmelting(NetherX.oreMalite.blockID, new ItemStack(NetherX.malite), 6.0f);
        GameRegistry.addSmelting(Block.slowSand.blockID, new ItemStack(NetherX.soulglass), 6.0f);
        GameRegistry.addSmelting(NetherX.oreNecromite.blockID, new ItemStack(NetherX.necromite), 8.0f);
        GameRegistry.addSmelting(NetherX.glutroot.itemID, new ItemStack(Item.dyePowder, 1, 5), 1.0f);
        GameRegistry.addShapelessRecipe(new ItemStack(NetherX.bowlGlutrootSoup), new Object[] { Item.bowlEmpty, NetherX.glutroot });
        GameRegistry.addRecipe(new ItemStack(Item.glassBottle, 3), new Object[] { "#0#", "0#0", '#', NetherX.soulglass });
        GameRegistry.addRecipe(new ItemStack(NetherX.vileplanks, 4), new Object[] { "#", '#', NetherX.vilewood });
        GameRegistry.addRecipe(new ItemStack(Item.stick, 4), new Object[] { "#", "#", '#', NetherX.vileplanks });
        GameRegistry.addRecipe(new ItemStack(Block.workbench), new Object[] { "##", "##", '#', NetherX.vileplanks });
        GameRegistry.addRecipe(new ItemStack(NetherX.torchGlowstone), new Object[] { "X", "#", '#', Item.stick, 'X', Item.glowstone });
        GameRegistry.addRecipe(new ItemStack(NetherX.axeMalite), new Object[] { "XX0", "XI0", "0I0", 'X', NetherX.malite, 'I', Item.stick });
        GameRegistry.addRecipe(new ItemStack(NetherX.axeMalite), new Object[] { "0XX", "0IX", "0I0", 'X', NetherX.malite, 'I', Item.stick });
        GameRegistry.addRecipe(new ItemStack(NetherX.swordMalite), new Object[] { "0X0", "0X0", "0I0", 'X', NetherX.malite, 'I', Item.stick });
        GameRegistry.addRecipe(new ItemStack(NetherX.pickaxeMalite), new Object[] { "XXX", "0I0", "0I0", 'X', NetherX.malite, 'I', Item.stick });
        GameRegistry.addRecipe(new ItemStack(NetherX.shovelMalite), new Object[] { "0X0", "0I0", "0I0", 'X', NetherX.malite, 'I', Item.stick });
        GameRegistry.addRecipe(new ItemStack(NetherX.axeNetherrack), new Object[] { "XX0", "XI0", "0I0", 'X', Block.netherrack, 'I', Item.stick });
        GameRegistry.addRecipe(new ItemStack(NetherX.axeNetherrack), new Object[] { "0XX", "0IX", "0I0", 'X', Block.netherrack, 'I', Item.stick });
        GameRegistry.addRecipe(new ItemStack(NetherX.swordNetherrack), new Object[] { "0X0", "0X0", "0I0", 'X', Block.netherrack, 'I', Item.stick });
        GameRegistry.addRecipe(new ItemStack(NetherX.pickaxeNetherrack), new Object[] { "XXX", "0I0", "0I0", 'X', Block.netherrack, 'I', Item.stick });
        GameRegistry.addRecipe(new ItemStack(NetherX.shovelNetherrack), new Object[] { "0X0", "0I0", "0I0", 'X', Block.netherrack, 'I', Item.stick });
        GameRegistry.addRecipe(new ItemStack(Item.axeWood), new Object[] { "XX0", "XI0", "0I0", 'X', NetherX.vileplanks, 'I', Item.stick });
        GameRegistry.addRecipe(new ItemStack(Item.axeWood), new Object[] { "0XX", "0IX", "0I0", 'X', NetherX.vileplanks, 'I', Item.stick });
        GameRegistry.addRecipe(new ItemStack(Item.swordWood), new Object[] { "0X0", "0X0", "0I0", 'X', NetherX.vileplanks, 'I', Item.stick });
        GameRegistry.addRecipe(new ItemStack(Item.pickaxeWood), new Object[] { "XXX", "0I0", "0I0", 'X', NetherX.vileplanks, 'I', Item.stick });
        GameRegistry.addRecipe(new ItemStack(Item.shovelWood), new Object[] { "0X0", "0I0", "0I0", 'X', NetherX.vileplanks, 'I', Item.stick });
        GameRegistry.addRecipe(new ItemStack(Item.hoeWood), new Object[] { "XX0", "0I0", "0I0", 'X', NetherX.vileplanks, 'I', Item.stick });
        GameRegistry.addRecipe(new ItemStack(Item.hoeWood), new Object[] { "0XX", "0I0", "0I0", 'X', NetherX.vileplanks, 'I', Item.stick });
        GameRegistry.addRecipe(new ItemStack(NetherX.axeNecromite), new Object[] { "XX0", "XI0", "0I0", 'X', NetherX.necromite, 'I', Item.stick });
        GameRegistry.addRecipe(new ItemStack(NetherX.axeNecromite), new Object[] { "0XX", "0IX", "0I0", 'X', NetherX.necromite, 'I', Item.stick });
        GameRegistry.addRecipe(new ItemStack(NetherX.swordNecromite), new Object[] { "0X0", "0X0", "0I0", 'X', NetherX.necromite, 'I', Item.stick });
        GameRegistry.addRecipe(new ItemStack(NetherX.pickaxeNecromite), new Object[] { "XXX", "0I0", "0I0", 'X', NetherX.necromite, 'I', Item.stick });
        GameRegistry.addRecipe(new ItemStack(NetherX.shovelNecromite), new Object[] { "0X0", "0I0", "0I0", 'X', NetherX.necromite, 'I', Item.stick });
        GameRegistry.addRecipe(new ItemStack(NetherX.blockMalite), new Object[] { "XXX", "XXX", "XXX", 'X', NetherX.malite });
        GameRegistry.addRecipe(new ItemStack(NetherX.blockNecromite), new Object[] { "XXX", "XXX", "XXX", 'X', NetherX.necromite });
        GameRegistry.addRecipe(new ItemStack(Item.bowlEmpty, 4), new Object[] { "X0X", "0X0", 'X', NetherX.vileplanks });
        GameRegistry.addRecipe(new ItemStack((Block)Block.chest), new Object[] { "XXX", "X0X", "XXX", 'X', NetherX.vileplanks });
        GameRegistry.addRecipe(new ItemStack(Block.pressurePlatePlanks), new Object[] { "XX", 'X', NetherX.vileplanks });
        GameRegistry.addRecipe(new ItemStack(NetherX.plateObsidian), new Object[] { "XX", 'X', Block.obsidian });
        GameRegistry.addRecipe(new ItemStack(NetherX.malite, 9), new Object[] { "X", 'X', NetherX.blockMalite });
        GameRegistry.addRecipe(new ItemStack(NetherX.necromite, 9), new Object[] { "X", 'X', NetherX.blockNecromite });
        GameRegistry.addRecipe(new ItemStack((Item)NetherX.helmetMalite), new Object[] { "XXX", "X X", 'X', NetherX.malite });
        GameRegistry.addRecipe(new ItemStack((Item)NetherX.helmetNecromite), new Object[] { "XXX", "X X", 'X', NetherX.necromite });
        GameRegistry.addRecipe(new ItemStack((Item)NetherX.helmetMagma), new Object[] { "XXX", "X X", 'X', NetherX.magmaCrystal });
        GameRegistry.addRecipe(new ItemStack((Item)NetherX.plateMalite), new Object[] { "X X", "XXX", "XXX", 'X', NetherX.malite });
        GameRegistry.addRecipe(new ItemStack((Item)NetherX.plateNecromite), new Object[] { "X X", "XXX", "XXX", 'X', NetherX.necromite });
        GameRegistry.addRecipe(new ItemStack((Item)NetherX.plateMagma), new Object[] { "X X", "XXX", "XXX", 'X', NetherX.magmaCrystal });
        GameRegistry.addRecipe(new ItemStack((Item)NetherX.legsMalite), new Object[] { "XXX", "X X", "X X", 'X', NetherX.malite });
        GameRegistry.addRecipe(new ItemStack((Item)NetherX.legsNecromite), new Object[] { "XXX", "X X", "X X", 'X', NetherX.necromite });
        GameRegistry.addRecipe(new ItemStack((Item)NetherX.legsMagma), new Object[] { "XXX", "X X", "X X", 'X', NetherX.magmaCrystal });
        GameRegistry.addRecipe(new ItemStack((Item)NetherX.bootsMalite), new Object[] { "X X", "X X", 'X', NetherX.malite });
        GameRegistry.addRecipe(new ItemStack((Item)NetherX.bootsNecromite), new Object[] { "X X", "X X", 'X', NetherX.necromite });
        GameRegistry.addRecipe(new ItemStack((Item)NetherX.bootsMagma), new Object[] { "X X", "X X", 'X', NetherX.magmaCrystal });
        GameRegistry.addRecipe(new ItemStack(NetherX.poisonbucketEmpty), new Object[] { "X X", " X ", 'X', NetherX.malite });
        GameRegistry.addRecipe(new ItemStack(NetherX.itemcrystalcauldron), new Object[] { "X X", "X X", "XXX", 'X', Item.netherQuartz });
        GameRegistry.addRecipe(new ItemStack(NetherX.stairsWoodVile), new Object[] { "X  ", "XX ", "XXX", 'X', NetherX.vileplanks });
        GameRegistry.addRecipe(new ItemStack(NetherX.stairsWoodVile), new Object[] { "  X", " XX", "XXX", 'X', NetherX.vileplanks });
        GameRegistry.addRecipe(new ItemStack(Block.woodenButton), new Object[] { "X", 'X', NetherX.vileplanks });
        GameRegistry.addRecipe(new ItemStack(Item.doorWood), new Object[] { "XX", "XX", "XX", 'X', NetherX.vileplanks });
        GameRegistry.addRecipe(new ItemStack(NetherX.doorObsidianPlacer), new Object[] { "XX", "XX", "XX", 'X', Block.obsidian });
        GameRegistry.addRecipe(new ItemStack(Item.bed), new Object[] { "XXX", "SSS", 'X', Block.cloth, 'S', NetherX.vileplanks });
        GameRegistry.addRecipe(new ItemStack(NetherX.soulglassPane, 16), new Object[] { "XXX", "XXX", 'X', NetherX.soulglass });
        GameRegistry.addRecipe(new ItemStack(NetherX.chiseledNetherrack, 4), new Object[] { "XX", "XX", 'X', Block.netherrack });
        GameRegistry.addRecipe(new ItemStack(NetherX.netherShrine), new Object[] { "OOO", "XGX", "XXX", 'O', Block.obsidian, 'X', Item.netherrackBrick, 'G', Item.ghastTear });
        GameRegistry.addRecipe(new ItemStack(NetherX.netherShrine), new Object[] { "OOO", "XGX", "XXX", 'O', Block.obsidian, 'X', Block.netherBrick, 'G', Item.ghastTear });
        GameRegistry.addRecipe(new ItemStack(NetherX.obsidianBoat), new Object[] { "X X", "XXX", 'X', Block.obsidian });
        GameRegistry.addShapelessRecipe(new ItemStack(NetherX.magmaCrystal), new Object[] { Item.netherQuartz, Item.magmaCream });
        if (NetherX.enableIronCrafting) {
            GameRegistry.addShapelessRecipe(new ItemStack(Item.ingotIron), new Object[] { NetherX.ichoriteShard, NetherX.malite });
        }
        GameRegistry.addRecipe(new ItemStack(NetherX.infernoStaff), new Object[] { "0X0", "0I0", "0I0", 'X', NetherX.ghastEgg, 'I', Item.blazeRod });
        GameRegistry.addRecipe(new ItemStack(NetherX.infernoStaff), new Object[] { "X00", "0I0", "00I", 'X', NetherX.ghastEgg, 'I', Item.blazeRod });
        GameRegistry.addRecipe(new ItemStack(NetherX.infernoStaff), new Object[] { "00X", "0I0", "I00", 'X', NetherX.ghastEgg, 'I', Item.blazeRod });
        GameRegistry.addRecipe(new ItemStack(NetherX.netherbomb), new Object[] { "GSG", "SGS", "GSG", 'G', Item.gunpowder, 'S', Block.slowSand });
        if (!NetherX.netherFurnaceRequireNetherQuartz) {
            GameRegistry.addRecipe(new ItemStack(NetherX.netherfurnaceIdle), new Object[] { "XXX", "X X", "XXX", 'X', Block.netherrack });
        }
        else {
            GameRegistry.addRecipe(new ItemStack(NetherX.netherfurnaceIdle), new Object[] { "XXX", "XNX", "XXX", 'X', Block.netherrack, 'N', Item.netherQuartz });
        }
        GameRegistry.addShapelessRecipe(new ItemStack(NetherX.bookCursed), new Object[] { NetherX.blackpaper, NetherX.blackpaper, NetherX.blackpaper, Item.leather });
        GameRegistry.addShapelessRecipe(new ItemStack(Item.fireballCharge), new Object[] { NetherX.blackpaper, Item.blazePowder, Item.gunpowder });
        GameRegistry.addRecipe(new ItemStack(NetherX.execrationTable), new Object[] { " B ", "NON", "OOO", 'B', NetherX.bookCursed, 'N', NetherX.necromite, 'O', Block.obsidian });
        GameRegistry.addRecipe(new ItemStack(NetherX.stairsNetherrack), new Object[] { "C  ", "CC ", "CCC", 'C', NetherX.chiseledNetherrack });
        GameRegistry.addRecipe(new ItemStack(NetherX.stairsNetherrack), new Object[] { "  C", " CC", "CCC", 'C', NetherX.chiseledNetherrack });
        GameRegistry.addSmelting(NetherX.chiseledNetherrack.blockID, new ItemStack(NetherX.chiseledNetherrackCharred), 0.0f);
        GameRegistry.registerWorldGenerator((IWorldGenerator)this.eventmanager);
        GameRegistry.registerWorldGenerator((IWorldGenerator)this.oremanager);
        GameRegistry.addRecipe(new ItemStack(NetherX.vilewoodSingleSlab, 6), new Object[] { "XXX", 'X', NetherX.vileplanks });
        GameRegistry.addRecipe(new ItemStack(NetherX.netherrackSingleSlab, 6), new Object[] { "XXX", 'X', NetherX.chiseledNetherrack });
        GameRegistry.addRecipe(new ItemStack((Block)Block.daylightSensor), new Object[] { "GGG", "QQQ", "XXX", 'G', Block.glass, 'Q', Item.netherQuartz, 'X', NetherX.vilewoodSingleSlab });
        GameRegistry.addRecipe(new ItemStack((Block)Block.daylightSensor), new Object[] { "GGG", "QQQ", "XXX", 'G', NetherX.soulglass, 'Q', Item.netherQuartz, 'X', NetherX.vilewoodSingleSlab });
        GameRegistry.addRecipe(new ItemStack((Block)Block.daylightSensor), new Object[] { "GGG", "QQQ", "XXX", 'G', NetherX.soulglass, 'Q', Item.netherQuartz, 'X', Block.woodSingleSlab });
        GameRegistry.registerFuelHandler((IFuelHandler)new NXFuelHandler());
        MinecraftForge.EVENT_BUS.register((Object)new PigZombieHandler());
        FluidContainerRegistry.registerFluidContainer(FluidRegistry.getFluidStack("poison", 1000), new ItemStack(NetherX.poisonbucketPoison), new ItemStack(NetherX.poisonbucketEmpty));
    }

    @Mod.EventHandler
    public void postInit(final FMLPostInitializationEvent event) {
        Item.itemsList[NetherX.vilewoodSingleSlab.blockID] = (Item)new ItemSlab(NetherX.vilewoodSingleSlab.blockID - 256, (BlockHalfSlab)NetherX.vilewoodSingleSlab, (BlockHalfSlab)NetherX.vilewoodDoubleSlab, false);
        Item.itemsList[NetherX.netherrackSingleSlab.blockID] = (Item)new ItemSlab(NetherX.netherrackSingleSlab.blockID - 256, (BlockHalfSlab)NetherX.netherrackSingleSlab, (BlockHalfSlab)NetherX.netherrackDoubleSlab, false);
    }

    public static int getUniqueEntityId() {
        do {
            ++NetherX.startEntityId;
        } while (EntityList.getStringFromID(NetherX.startEntityId) != null);
        return NetherX.startEntityId;
    }

    public static void registerEntityEgg(final Class<? extends Entity> entity, final int primaryColor, final int secondaryColor) {
        final int id = getUniqueEntityId();
        EntityList.IDtoClassMapping.put(id, entity);
        EntityList.entityEggs.put(id, new EntityEggInfo(id, primaryColor, secondaryColor));
    }

    static {
        NetherX.instance = new NetherX();
        NetherX.startEntityId = 300;
        NetherX.bite = (DamageSource)new NetherDamageSource("bite");
        NetherX.MALITE = EnumHelper.addToolMaterial("MALITE", 2, 200, 5.5f, 2.0f, 4);
        NetherX.NETHERRACK = EnumHelper.addToolMaterial("NETHERRACK", 1, 100, 6.0f, 1.0f, 3);
        NetherX.NETHERRACKCURSED = EnumHelper.addToolMaterial("NETHERRACKCURSED", 1, 150, 11.0f, 1.0f, 3);
        NetherX.NECROMITE = EnumHelper.addToolMaterial("NECROMITE", 3, 1061, 3.0f, 2.5f, 5);
        NetherX.MALITEARMOR = EnumHelper.addArmorMaterial("poison", 12, new int[] { 2, 5, 5, 1 }, 18);
        NetherX.bucketEmpty = new ItemNXBucket(69, 0).setUnlocalizedName("bucket").setMaxStackSize(16).setTextureName("bucket_empty");
        NetherX.glassBottle = new ItemNXGlassBottle(118).setUnlocalizedName("glassBottle").setTextureName("potion_bottle_empty");
        NetherX.poison = new PoisonFluid("poison");
    }
}
