//Deobfuscated with https://github.com/SimplyProgrammer/Minecraft-Deobfuscator3000 using mappings "Z:\home\aaron\Files\Minecraft Stuff\Mods\Mod Code Stuff\mcp811\conf"!

//Decompiled by Procyon!

package biomesoplenty.api;

import com.google.common.base.*;
import net.minecraft.world.biome.*;
import java.util.*;

public class Biomes
{
    public static Optional<? extends BiomeGenBase> alps;
    public static Optional<? extends BiomeGenBase> alpsForest;
    public static Optional<? extends BiomeGenBase> alpsBase;
    public static Optional<? extends BiomeGenBase> arctic;
    public static Optional<? extends BiomeGenBase> autumnHills;
    public static Optional<? extends BiomeGenBase> badlands;
    public static Optional<? extends BiomeGenBase> bambooForest;
    public static Optional<? extends BiomeGenBase> bayou;
    public static Optional<? extends BiomeGenBase> beachGravel;
    public static Optional<? extends BiomeGenBase> beachOvergrown;
    public static Optional<? extends BiomeGenBase> birchForest;
    public static Optional<? extends BiomeGenBase> bog;
    public static Optional<? extends BiomeGenBase> borealForest;
    public static Optional<? extends BiomeGenBase> brushland;
    public static Optional<? extends BiomeGenBase> canyon;
    public static Optional<? extends BiomeGenBase> canyonRavine;
    public static Optional<? extends BiomeGenBase> chaparral;
    public static Optional<? extends BiomeGenBase> cherryBlossomGrove;
    public static Optional<? extends BiomeGenBase> coniferousForest;
    public static Optional<? extends BiomeGenBase> coniferousForestSnow;
    public static Optional<? extends BiomeGenBase> crag;
    public static Optional<? extends BiomeGenBase> deadForest;
    public static Optional<? extends BiomeGenBase> deadForestSnow;
    public static Optional<? extends BiomeGenBase> deadSwamp;
    public static Optional<? extends BiomeGenBase> deadlands;
    public static Optional<? extends BiomeGenBase> deciduousForest;
    public static Optional<? extends BiomeGenBase> dunes;
    public static Optional<? extends BiomeGenBase> fen;
    public static Optional<? extends BiomeGenBase> field;
    public static Optional<? extends BiomeGenBase> fieldForest;
    public static Optional<? extends BiomeGenBase> frostForest;
    public static Optional<? extends BiomeGenBase> fungiForest;
    public static Optional<? extends BiomeGenBase> garden;
    public static Optional<? extends BiomeGenBase> glacier;
    public static Optional<? extends BiomeGenBase> grassland;
    public static Optional<? extends BiomeGenBase> grove;
    public static Optional<? extends BiomeGenBase> heathland;
    public static Optional<? extends BiomeGenBase> highland;
    public static Optional<? extends BiomeGenBase> hotSprings;
    public static Optional<? extends BiomeGenBase> icyHills;
    public static Optional<? extends BiomeGenBase> jadeCliffs;
    public static Optional<? extends BiomeGenBase> lavenderFields;
    public static Optional<? extends BiomeGenBase> lushDesert;
    public static Optional<? extends BiomeGenBase> lushSwamp;
    public static Optional<? extends BiomeGenBase> mangrove;
    public static Optional<? extends BiomeGenBase> mapleWoods;
    public static Optional<? extends BiomeGenBase> marsh;
    public static Optional<? extends BiomeGenBase> meadow;
    public static Optional<? extends BiomeGenBase> meadowForest;
    public static Optional<? extends BiomeGenBase> mesa;
    public static Optional<? extends BiomeGenBase> moor;
    public static Optional<? extends BiomeGenBase> mountain;
    public static Optional<? extends BiomeGenBase> mysticGrove;
    public static Optional<? extends BiomeGenBase> netherBase;
    public static Optional<? extends BiomeGenBase> netherGarden;
    public static Optional<? extends BiomeGenBase> netherDesert;
    public static Optional<? extends BiomeGenBase> netherLava;
    public static Optional<? extends BiomeGenBase> netherBone;
    public static Optional<? extends BiomeGenBase> oasis;
    public static Optional<? extends BiomeGenBase> oceanAbyss;
    public static Optional<? extends BiomeGenBase> oceanCoral;
    public static Optional<? extends BiomeGenBase> oceanKelp;
    public static Optional<? extends BiomeGenBase> ominousWoods;
    public static Optional<? extends BiomeGenBase> ominousWoodsThick;
    public static Optional<? extends BiomeGenBase> orchard;
    public static Optional<? extends BiomeGenBase> originValley;
    public static Optional<? extends BiomeGenBase> outback;
    public static Optional<? extends BiomeGenBase> overgrownGreens;
    public static Optional<? extends BiomeGenBase> pasture;
    public static Optional<? extends BiomeGenBase> pastureMeadow;
    public static Optional<? extends BiomeGenBase> pastureThin;
    public static Optional<? extends BiomeGenBase> polar;
    public static Optional<? extends BiomeGenBase> prairie;
    public static Optional<? extends BiomeGenBase> promisedLandForest;
    public static Optional<? extends BiomeGenBase> promisedLandPlains;
    public static Optional<? extends BiomeGenBase> promisedLandSwamp;
    public static Optional<? extends BiomeGenBase> quagmire;
    public static Optional<? extends BiomeGenBase> rainforest;
    public static Optional<? extends BiomeGenBase> redwoodForest;
    public static Optional<? extends BiomeGenBase> sacredSprings;
    public static Optional<? extends BiomeGenBase> savanna;
    public static Optional<? extends BiomeGenBase> savannaPlateau;
    public static Optional<? extends BiomeGenBase> scrubland;
    public static Optional<? extends BiomeGenBase> seasonalForest;
    public static Optional<? extends BiomeGenBase> seasonalSpruceForest;
    public static Optional<? extends BiomeGenBase> shield;
    public static Optional<? extends BiomeGenBase> shore;
    public static Optional<? extends BiomeGenBase> shrubland;
    public static Optional<? extends BiomeGenBase> shrublandForest;
    public static Optional<? extends BiomeGenBase> silkglades;
    public static Optional<? extends BiomeGenBase> sludgepit;
    public static Optional<? extends BiomeGenBase> spruceWoods;
    public static Optional<? extends BiomeGenBase> steppe;
    public static Optional<? extends BiomeGenBase> temperateRainforest;
    public static Optional<? extends BiomeGenBase> thicket;
    public static Optional<? extends BiomeGenBase> timber;
    public static Optional<? extends BiomeGenBase> timberThin;
    public static Optional<? extends BiomeGenBase> tropicalRainforest;
    public static Optional<? extends BiomeGenBase> tropics;
    public static Optional<? extends BiomeGenBase> tropicsMountain;
    public static Optional<? extends BiomeGenBase> tundra;
    public static Optional<? extends BiomeGenBase> volcano;
    public static Optional<? extends BiomeGenBase> wasteland;
    public static Optional<? extends BiomeGenBase> wetland;
    public static Optional<? extends BiomeGenBase> woodland;
    public static Optional<? extends BiomeGenBase> plainsNew;
    public static Optional<? extends BiomeGenBase> desertNew;
    public static Optional<? extends BiomeGenBase> extremeHillsNew;
    public static Optional<? extends BiomeGenBase> forestNew;
    public static Optional<? extends BiomeGenBase> forestHillsNew;
    public static Optional<? extends BiomeGenBase> taigaNew;
    public static Optional<? extends BiomeGenBase> taigaHillsNew;
    public static Optional<? extends BiomeGenBase> swamplandNew;
    public static Optional<? extends BiomeGenBase> jungleNew;
    public static Optional<? extends BiomeGenBase> jungleHillsNew;
    public static ArrayList<BiomeGenBase> netherBiomes;
    
    static {
        Biomes.alps = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.alpsForest = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.alpsBase = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.arctic = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.autumnHills = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.badlands = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.bambooForest = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.bayou = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.beachGravel = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.beachOvergrown = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.birchForest = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.bog = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.borealForest = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.brushland = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.canyon = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.canyonRavine = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.chaparral = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.cherryBlossomGrove = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.coniferousForest = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.coniferousForestSnow = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.crag = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.deadForest = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.deadForestSnow = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.deadSwamp = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.deadlands = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.deciduousForest = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.dunes = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.fen = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.field = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.fieldForest = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.frostForest = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.fungiForest = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.garden = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.glacier = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.grassland = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.grove = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.heathland = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.highland = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.hotSprings = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.icyHills = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.jadeCliffs = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.lavenderFields = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.lushDesert = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.lushSwamp = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.mangrove = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.mapleWoods = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.marsh = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.meadow = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.meadowForest = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.mesa = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.moor = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.mountain = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.mysticGrove = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.netherBase = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.netherGarden = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.netherDesert = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.netherLava = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.netherBone = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.oasis = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.oceanAbyss = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.oceanCoral = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.oceanKelp = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.ominousWoods = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.ominousWoodsThick = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.orchard = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.originValley = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.outback = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.overgrownGreens = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.pasture = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.pastureMeadow = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.pastureThin = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.polar = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.prairie = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.promisedLandForest = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.promisedLandPlains = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.promisedLandSwamp = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.quagmire = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.rainforest = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.redwoodForest = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.sacredSprings = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.savanna = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.savannaPlateau = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.scrubland = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.seasonalForest = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.seasonalSpruceForest = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.shield = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.shore = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.shrubland = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.shrublandForest = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.silkglades = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.sludgepit = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.spruceWoods = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.steppe = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.temperateRainforest = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.thicket = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.timber = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.timberThin = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.tropicalRainforest = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.tropics = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.tropicsMountain = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.tundra = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.volcano = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.wasteland = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.wetland = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.woodland = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.plainsNew = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.desertNew = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.extremeHillsNew = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.forestNew = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.forestHillsNew = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.taigaNew = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.taigaHillsNew = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.swamplandNew = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.jungleNew = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.jungleHillsNew = (Optional<? extends BiomeGenBase>)Optional.absent();
        Biomes.netherBiomes = new ArrayList<BiomeGenBase>();
    }
}
